import * as path from 'path';
import * as fs from 'fs';
import { getBaseUrl } from '../../../TestData/Excel_Reader/excelReader';

const TOKEN_FILE_PATH = path.resolve(__dirname, '../../../TestData/authToken.json');

/**
 * Reads the latest saved Bearer token generated by 'npm run test:login'.
 */
export function getSavedAuthToken(): string {
  try {
    if (fs.existsSync(TOKEN_FILE_PATH)) {
      const data = JSON.parse(fs.readFileSync(TOKEN_FILE_PATH, 'utf-8'));
      return data.accessToken || '';
    }
  } catch (err: any) {
    console.warn('[Auth] Could not read authToken.json:', err.message);
  }
  return '';
}

/**
 * Returns gateway headers with Authorization Bearer token.
 * If token is not explicitly passed, it automatically uses getSavedAuthToken().
 */
export function getDefaultGatewayHeaders(token?: string, overrides?: Record<string, string>): Record<string, string> {
  const activeToken = token || getSavedAuthToken();

  const headers: Record<string, string> = {
    'x-user-id': '00000000-0000-0000-0000-000000000001',
    'x-company-id': '00000000-0000-0000-0000-000000000002',
    'Content-Type': 'application/json',
    ...(overrides || {}),
  };

  if (activeToken) {
    headers['Authorization'] = `Bearer ${activeToken}`;
  }

  return headers;
}

export function getFranchiseBaseUrl(): string {
  return getBaseUrl('Environment');
}
